# Generated by Django 2.1.3 on 2019-01-06 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20190106_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrecord',
            name='topic',
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.Webpage'),
        ),
    ]
